# Generated by Django 3.2.4 on 2021-07-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
                ('title', models.CharField(max_length=50)),
                ('head0', models.CharField(default='', max_length=500)),
                ('contentHead0', models.CharField(default='', max_length=5000)),
                ('head1', models.CharField(default='', max_length=500)),
                ('contentHead1', models.CharField(default='', max_length=5000)),
                ('head2', models.CharField(default='', max_length=500)),
                ('contentHead2', models.CharField(default='', max_length=5000)),
                ('publishDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
